import type { Activity, Application, Job } from "@/lib/types";

export const demoJobs: Job[] = [
  {
    id: "job-1",
    source: "Naukri",
    externalId: "gh-101",
    company: "Stripe",
    companyInitial: "S",
    companyColor: "from-indigo-500 to-purple-600",
    title: "Senior Staff Frontend Engineer",
    location: "San Francisco, CA",
    workMode: "Hybrid",
    employmentType: "Full-time",
    seniority: "Senior Staff",
    salary: "$210,000 - $260,000",
    tags: ["React", "TypeScript", "Design Systems", "WebAssembly"],
    matchScore: 96,
    matchReasons: ["Strong React & TS alignment", "Design systems leadership", "High salary bracket match"],
    postedLabel: "2h ago",
    postedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    description: "Architect Next.js core design patterns & high performance web checkout interfaces across global products.",
    applyUrl: "https://stripe.com/jobs",
    status: "open",
  },
  {
    id: "job-2",
    source: "Instahyre",
    externalId: "lev-202",
    company: "Linear",
    companyInitial: "L",
    companyColor: "from-blue-500 to-cyan-500",
    title: "Principal Product Designer",
    location: "Remote (US/EU)",
    workMode: "Remote",
    employmentType: "Full-time",
    seniority: "Principal",
    salary: "$190,000 - $240,000",
    tags: ["Figma", "UI Animation", "Product Strategy", "Micro-interactions"],
    matchScore: 92,
    matchReasons: ["Craft & Polish focus", "Remote native flexibility", "Matched target seniority"],
    postedLabel: "5h ago",
    postedAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    description: "Craft state of the art issue tracking interfaces with lightning speed keyboard navigation and micro-animations.",
    applyUrl: "https://linear.app/careers",
    status: "open",
  },
  {
    id: "job-3",
    source: "IIMJobs",
    externalId: "wk-303",
    company: "Vercel",
    companyInitial: "V",
    companyColor: "from-slate-900 to-zinc-700",
    title: "AI Infrastructure Engineer",
    location: "New York, NY",
    workMode: "Remote",
    employmentType: "Full-time",
    seniority: "Senior",
    salary: "$185,000 - $235,000",
    tags: ["Next.js", "Python", "LLMs", "Edge Computing"],
    matchScore: 89,
    matchReasons: ["Vercel Ecosystem expert", "Edge network experience"],
    postedLabel: "1d ago",
    postedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    description: "Scale v0 and Vercel AI SDK runtime endpoints for millions of sub-second streaming inference calls.",
    applyUrl: "https://vercel.com/careers",
    status: "open",
  },
];

export const demoApplications: Application[] = [
  {
    id: "app-1",
    jobId: "job-1",
    company: "Stripe",
    role: "Senior Staff Frontend Engineer",
    state: "ready_for_review",
    updatedLabel: "Just now",
    source: "Naukri",
    nextAction: "Review tailored resume & AI cover letter draft",
  },
  {
    id: "app-2",
    jobId: "job-2",
    company: "Linear",
    role: "Principal Product Designer",
    state: "submitted",
    updatedLabel: "Yesterday",
    source: "Instahyre",
    nextAction: "Awaiting Recruiter Screen response",
  },
];

export const demoActivity: Activity[] = [
  {
    id: "act-1",
    type: "jobs",
    title: "New Match Identified",
    detail: "Stripe - Senior Staff Frontend Engineer (96% Match)",
    time: "2h ago",
  },
  {
    id: "act-2",
    type: "application",
    title: "Resume Tailored",
    detail: "Generated ATS-optimized resume for Linear application",
    time: "Yesterday",
  },
];

export const demoProfile = {
  fullName: "Alex Rivera",
  headline: "Staff Product Engineer & UI Craftsman",
  email: "alex.rivera@example.com",
  phone: "+1 (555) 234-5678",
  location: "San Francisco, CA",
  summary: "10+ years building high performance React interfaces, design systems, and AI-assisted workflow engines.",
  skills: ["React 19", "TypeScript", "Next.js", "Tailwind CSS", "GSAP", "AI Agent Integrations"],
  targetRoles: ["Frontend Engineer", "Staff Engineer", "Product Engineer"],
  experiences: [
    {
      company: "Northstar Labs",
      title: "Staff Product Engineer",
      startDate: "2022-01-01",
      endDate: null,
      description: "Led product engineering and AI-assisted workflow delivery.",
    },
  ],
  education: [
    {
      institution: "University of California",
      degree: "B.S.",
      fieldOfStudy: "Computer Science",
    },
  ],
  projects: [],
  certifications: [],
};
